name: fortl-implementation
version: '0.1.2'
synopsis: A modern language for science
author: Dominic Orchard
copyright: 2024 authors
license: BSD3
dependencies:
- base >=4.10 && <5
- text
- array
- transformers
- containers
- directory
- filepath

ghc-options:
- -O0
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-unused-matches
- -Wno-name-shadowing
- -Wno-type-defaults

executables:
  fortl:
    main: Lang/Frontend.hs
    source-dirs: src
    ghc-options: -main-is Lang.Frontend
    build-tools:
     - alex
     - happy
    dependencies:
     - fortl-implementation

  # fortli:
  #   main: Lang/REPL.hs
  #   source-dirs: src
  #   ghc-options: -main-is Lang.REPL
  #   build-tools:
  #    - alex
  #    - happy
  #   dependencies:
  #    - fortl-implementation

library:
  source-dirs: src
  exposed-modules:
  - Lang.Semantics
  - Lang.Syntax
  - Lang.Parser
  - Lang.PrettyPrint
  - Lang.Descriptions

tests:
  fortl-golden:
    main: Spec.hs
    source-dirs: tests
    dependencies:
    - fortl-implementation
    - strict
    - Diff
    - tasty
    - tasty-golden